name:                tfl-tube
version:             0.1.0.0
github:              githubuser/tfl-tube
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2017 Edwin Kadavy

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/tfl-tube#readme>

dependencies:
- base >=4.3 && <5
- http-conduit >= 2.2.4
- bytestring >= 0.10.8.1
- aeson >= 1.2.3.0
- generic-deriving >= 1.12
- HDBC >= 2.4.0.2
- HDBC-sqlite3 >= 2.3.3.1


library:
  source-dirs: src

executables:
  tfl-tube-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tfl-tube

tests:
  tfl-tube-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tfl-tube
